# Generated by Django 2.0 on 2018-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Deutsch', max_length=64),
            preserve_default=False,
        ),
    ]
