# Generated by Django 2.0 on 2018-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['lastName', 'firstName']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['dueBack']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='date_of_birth',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='date_of_death',
            new_name='deathDate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_back',
            new_name='dueBack',
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(default='German', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='yearPublished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='currentPrice',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
